server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://47.99.147.13:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a1818547
  jackson:
    time-zone: GMT+8
    date-format: yy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:com/example/edu/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
feign:
  hystrix:
    enabled: true

