server:
  port: 8003
spring:
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-vod
aliyun:
  vod:
    file:
      id: LTAI5t6Nkk9Xz7TT77A28i1h
      secret: jnLafs2SRjZPErgCDcozrp61sqxhWD