spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5t6Nkk9Xz7TT77A28i1h
      keysecret: jnLafs2SRjZPErgCDcozrp61sqxhWD
      bucketname: edu-guli119
server:
  port: 8002