server:
  port: 8004
spring:
  application:
    name: service-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.147.13:3306/guli?serverTimezone=GMT%2B8
    password: a1818547
    username: root
  jackson:
    time-zone: GMT+8
    date-format: yy-MM-dd HH:mm:ss
  redis:
    host: 47.99.147.13
    port: 6379
    database: 0
    timeout: 2000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: 1
mybatis-plus:
  mapper-locations: classpath:com/example/cms/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0
#feign:
#  hystrix:
#    enabled: true
#hystrix:
#  metrics:
#    polling-interval-ms: 3000