server:
  port: 8009
spring:
  application:
    name: service-acl
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://******:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ******
    password: *********
  jackson:
    time-zone: GMT+8
    date-format: yy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: **********

mybatis-plus:
  mapper-locations: classpath:com/example/acl/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



