server:
  port: 10000
spring:
  application:
    name: service-canal
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a1818547